---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: echo-staging
  namespace: staging
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:staging-*
spec:
  releaseName: echo-staging
  chart:
    git: git@github.com:tomikonio/gitops
    path: helm-charts/echo
    ref: master
  values:
    image: shukiyahu/echo_ex:staging-774cb54fe73e441543bf1f188ad5747f8912a498
    replicaCount: 1
    name: echo-staging
    namespace: staging
    data:
      mongodburl: "mongodb://echo:mypassword@mongo-mongodb.default.svc.cluster.local:27017/echo-staging"
