kind: ConfigMap 
apiVersion: v1 
metadata:
  name: echo
data:
  default.yaml: |
    port: "3000"
    loglevel: "debug"
    persist: "true"
    mongodburl: "mongodb://echo:mypassword@mongodb.default.svc.cluster.local:27017/echo"