---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: echo-production
  namespace: production
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.0
spec:
  releaseName: echo-production
  chart:
    git: git@github.com:tomikonio/gitops
    path: helm-charts/echo
    ref: master
  values:
    image: shukiyahu/echo_ex:1.0.30
    replicaCount: 1
    name: echo-production
    namespace: production
    hostname: ""
  rollback:
    # If set, will perform rollbacks for this release.
    enable: true
    # If set, will force resource update through delete/recreate if
    # needed.
    force: true
    # Prevent hooks from running during rollback.
    disableHooks: false
    # Time in seconds to wait for any individual Kubernetes operation.
    timeout: 300
    # If set, will wait until all Pods, PVCs, Services, and minimum
    # number of Pods of a Deployment are in a ready state before
    # marking the release as successful. It will wait for as long
    # as the set timeout.
    wait: false
