kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.name }}
type: Opaque
stringData:
  default.yaml: |
    port: {{ .Values.data.port }}
    loglevel: {{ .Values.data.loglevel }}
    persist: {{ .Values.data.persist }}
    mongodburl: {{ .Values.data.mongodburl }}
