apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.name }}
              servicePort: 80
