apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  default.yaml: |
    port: {{ .Values.data.port }}
    loglevel: {{ .Values.data.loglevel }}
    persist: {{ .Values.data.persist }}
    mongodburl: {{ .Values.data.mongodburl }}
  # Example:
  # password: {{ .Values.password | b64enc }}
